name: WebScraping
channels:
  - defaults
dependencies:
  - pip
  - requests
  - beautifulsoup4
  - numpy
  - pandas
  - matplotlib
  - python
  - pillow
  - bokeh
  - scipy=1.0.0
  - pymongo
  - scrapy==1.0.3
  - selenium
